version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    container_name: rest-app
    build:
      context: .
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db:
